### PR TITLE
Adam/mod

### PR DESCRIPTION
**Pull request by adcoh**
Customize progress bars, refactor and simplify credentials parsing, improve preprocessing, refactoring column validation, add option to remove stopwords, make pipeline more verbose

### CODE REVIEW

**Comment by adcoh** [comment]
I've checked that these changes are back-compatible with the old configuration of the pipeline

**Comment by Hernanros** [comment]
did you ran the script on any of the metrics?

**Comment by Hernanros** [comment]
I went over them, looks fine

**Comment by adcoh** [comment]
> did you ran the script on any of the metrics?

Yes, I tried with Bleu and Rouge, both worked

**Pull request merged**
